dbt_repo:
  outputs:
    dev:
      account: USCOCVL-CZ91277
      database: r1
      password: Goutham@8050813209
      role: ACCOUNTADMIN
      schema: staging
      threads: 1
      type: snowflake
      user: GOUTHAMHONG
      warehouse: COMPUTE_WH
  target: dev
